language: bash
before_script:
- chmod +x "./generate_img.sh"
script:
- "./generate_img.sh"
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: b23+/ow5uqIMykK2cGWisJC4gzixEdIhdFjSny+nCW0cyACEhHG2s8xvvFa4HEO5aHpdxThIDNpf+n9qZE/p3cZqvE84A6bEWb6xxRhLIKxdTqTbZuFkOsxsygNYaQn9H88yVZQJj0DzTb6zb227p9PxB5i/34v54gWrlzPHy9MLVJFQKAFwbLnG9PzOeLH+m34anq7xvm/t7MA3TI0igXKEIn3EckMsnx7kqH0bIa562ieV02hcUMOnjPeSMN3f4fZO6VIWcYSWzdmVjU6EHlEjDrCBd3fw9/uaqeBdQnhpEiVtOICpn7mUoK3xAJ3GBSiZJL2/5apNkWfV1ZWoXYwT5Hu9t0qu9gt+yCrppuYh6+6rf8wnmKbKAkAXTNyGyfI8bh9mCg14e3GAeH512WEsDvMiHrW12rk4ykkx40pWZErb5aqWlako6cEZmJUew6Q9PtA7ctnXzaII7L+EeYkWFVrQsPjiwKo60uIxfsI7hsU1DQA8ns0FQ5z2fSCHGqh4IxEUzWZlyK+tZU7HiwkfgyvJHBJMcfk3Tm3l4iX9FnwDxVRPEHCiCP6lR1g0Pxvs5Fa72AK4eR+m5YcVEsaA9zdMmlmz4E5p+WanrL17+uI4cFbpbAbMppDq3Cdjnza/fra1httSRZMJZQi5PlhvEZHqSRQsFBZ+S6MjKWU=
  file: ccu2-EnableSSH-$(cat ./VERSION).tar.gz
  on:
    repo: litti/ccu2-EnableSSH
    tags: true
    all_branches: true